Error: Not enough entropy error added
Sometimes hardware or software may not be having enough entropy buffered
to generate random values. In this case the software will retry finite
times and if we are not still able to generate enough entropy, it will
return a failure due to low entropy.

Signed-off-by: Abhiram S <abhiram.s@amd.com>